config/routes.rb
ISBNScanner::Application.routes.draw do
    require 'api'

    resources :publishers

    resources :books_publishers

    resources :authors_books

    resources :publisheds

    resources :authors

    resources :books

    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    get 'pages/home'

    mount Isbnscanner::API => '/'
    root 'pages#home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/author.rb
class Author < ActiveRecord::Base
    has_many :authors_book
    has_many :books, through: :authors_book
    validates_uniqueness_of :name
end

app/models/authors_book.rb
class AuthorsBook < ActiveRecord::Base
    belongs_to :author
    belongs_to :book
end

app/models/book.rb
class Book < ActiveRecord::Base
    has_many :authors_book
    has_many :authors, through: :authors_book
    has_many :books_publisher
    has_many :publishers, through: :books_publisher
    validates_uniqueness_of :isbn
end

app/models/books_publisher.rb
class BooksPublisher < ActiveRecord::Base
    belongs_to :book
    belongs_to :publisher
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
    has_many :books_publisher
    has_many :books, through: :books_publisher
    validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_books_controller.rb
class AuthorsBooksController < InheritedResources::Base
end

app/controllers/authors_controller.rb
class AuthorsController < InheritedResources::Base
end

app/controllers/books_controller.rb
class BooksController < InheritedResources::Base
end

app/controllers/books_publishers_controller.rb
class BooksPublishersController < InheritedResources::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home

    end
end

app/controllers/publishers_controller.rb
class PublishersController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_books_helper.rb
module AuthorsBooksHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/books_publishers_helper.rb
module BooksPublishersHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/authors/_form.html.haml
= form_for @author do |f|
  - if @author.errors.any?
    #error_explanation
      %h2= "#{pluralize(@author.errors.count, "error")} prohibited this author from being saved:"
      %ul
        - @author.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/authors/edit.html.haml
%h1 Editing author

= render 'form'

= link_to 'Show', @author
\|
= link_to 'Back', authors_path

app/views/authors/index.html.haml
%h1 Listing authors

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @authors.each do |author|
    %tr
      %td= author.name
      %td= link_to 'Show', author
      %td= link_to 'Edit', edit_author_path(author)
      %td= link_to 'Destroy', author, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Author', new_author_path

app/views/authors/new.html.haml
%h1 New author

= render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @author.name

= link_to 'Edit', edit_author_path(@author)
\|
= link_to 'Back', authors_path

app/views/authors_books/_form.html.haml
= form_for @authors_book do |f|
  - if @authors_book.errors.any?
    #error_explanation
      %h2= "#{pluralize(@authors_book.errors.count, "error")} prohibited this authors_book from being saved:"
      %ul
        - @authors_book.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :author_id
    = f.number_field :author_id
  .field
    = f.label :book_id
    = f.number_field :book_id
  .actions
    = f.submit 'Save'

app/views/authors_books/edit.html.haml
%h1 Editing authors_book

= render 'form'

= link_to 'Show', @authors_book
\|
= link_to 'Back', authors_books_path

app/views/authors_books/index.html.haml
%h1 Listing authors_books

%table
  %tr
    %th Author
    %th Book
    %th
    %th
    %th

  - @authors_books.each do |authors_book|
    %tr
      %td= authors_book.author_id
      %td= authors_book.book_id
      %td= link_to 'Show', authors_book
      %td= link_to 'Edit', edit_authors_book_path(authors_book)
      %td= link_to 'Destroy', authors_book, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Authors book', new_authors_book_path

app/views/authors_books/new.html.haml
%h1 New authors_book

= render 'form'

= link_to 'Back', authors_books_path

app/views/authors_books/show.html.haml
%p#notice= notice

%p
  %b Author:
  = @authors_book.author_id
%p
  %b Book:
  = @authors_book.book_id

= link_to 'Edit', edit_authors_book_path(@authors_book)
\|
= link_to 'Back', authors_books_path

app/views/books/_form.html.haml
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      %h2= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :isbn
    = f.text_field :isbn
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :image
    = f.text_field :image
  .field
    = f.label :published
    = f.text_field :published
  .actions
    = f.submit 'Save'

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @book
\|
= link_to 'Back', books_path

app/views/books/index.html.haml
%h1 Listing books

%table
  %tr
    %th Isbn
    %th Title
    %th Image
    %th Published
    %th
    %th
    %th

  - @books.each do |book|
    %tr
      %td= book.isbn
      %td= book.title
      %td= book.image
      %td= book.published
      %td= link_to 'Show', book
      %td= link_to 'Edit', edit_book_path(book)
      %td= link_to 'Destroy', book, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Book', new_book_path

app/views/books/new.html.haml
%h1 New book

= render 'form'

= link_to 'Back', books_path

app/views/books/show.html.haml
%p#notice= notice

%p
  %b Isbn:
  = @book.isbn
%p
  %b Title:
  = @book.title
%p
  %b Image:
  = @book.image
%p
  %b Published:
  = @book.published

= link_to 'Edit', edit_book_path(@book)
\|
= link_to 'Back', books_path

app/views/books_publishers/_form.html.haml
= form_for @books_publisher do |f|
  - if @books_publisher.errors.any?
    #error_explanation
      %h2= "#{pluralize(@books_publisher.errors.count, "error")} prohibited this books_publisher from being saved:"
      %ul
        - @books_publisher.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :book_id
    = f.number_field :book_id
  .field
    = f.label :publisher_id
    = f.number_field :publisher_id
  .actions
    = f.submit 'Save'

app/views/books_publishers/edit.html.haml
%h1 Editing books_publisher

= render 'form'

= link_to 'Show', @books_publisher
\|
= link_to 'Back', books_publishers_path

app/views/books_publishers/index.html.haml
%h1 Listing books_publishers

%table
  %tr
    %th Book
    %th Publisher
    %th
    %th
    %th

  - @books_publishers.each do |books_publisher|
    %tr
      %td= books_publisher.book_id
      %td= books_publisher.publisher_id
      %td= link_to 'Show', books_publisher
      %td= link_to 'Edit', edit_books_publisher_path(books_publisher)
      %td= link_to 'Destroy', books_publisher, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Books publisher', new_books_publisher_path

app/views/books_publishers/new.html.haml
%h1 New books_publisher

= render 'form'

= link_to 'Back', books_publishers_path

app/views/books_publishers/show.html.haml
%p#notice= notice

%p
  %b Book:
  = @books_publisher.book_id
%p
  %b Publisher:
  = @books_publisher.publisher_id

= link_to 'Edit', edit_books_publisher_path(@books_publisher)
\|
= link_to 'Back', books_publishers_path

app/views/layouts/application.html.haml
!!! html
%html
    %head
        %title ISBNScanner
        = stylesheet_link_tag "application"
        = javascript_include_tag "application"

    %body{style: 'overflow: hidden;'}
        #page-body
            = yield

app/views/pages/home.en.html.haml
.home
    .wrapper
        = image_tag "logo.png", alt: 'ISBN Scanner'

app/views/publishers/_form.html.haml
= form_for @publisher do |f|
  - if @publisher.errors.any?
    #error_explanation
      %h2= "#{pluralize(@publisher.errors.count, "error")} prohibited this publisher from being saved:"
      %ul
        - @publisher.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/publishers/edit.html.haml
%h1 Editing publisher

= render 'form'

= link_to 'Show', @publisher
\|
= link_to 'Back', publishers_path

app/views/publishers/index.html.haml
%h1 Listing publishers

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @publishers.each do |publisher|
    %tr
      %td= publisher.name
      %td= link_to 'Show', publisher
      %td= link_to 'Edit', edit_publisher_path(publisher)
      %td= link_to 'Destroy', publisher, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Publisher', new_publisher_path

app/views/publishers/new.html.haml
%h1 New publisher

= render 'form'

= link_to 'Back', publishers_path

app/views/publishers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @publisher.name

= link_to 'Edit', edit_publisher_path(@publisher)
\|
= link_to 'Back', publishers_path